version: "3.7"
services:
  app:
    container_name: "app"
    build: "."
    depends_on:
      - db
    ports:
      - 8088:8080
    environment:
      ENVIRONMENT: dev
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/gokitexample?sslmode=disable"
      HTTP_ADDR: ":8080"

  db:
    image: library/postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: gokitexample
